### ISSUE TITLE
Work plan for Gibbs sampling for hierarchical models

### ISSUE THREAD

**Issue by scidom** [JuliaStats/Klara.jl#155]
A functional `BasicGibbsJob` has been implemented [here](https://github.com/JuliaStats/Klara.jl/blob/master/src/jobs/BasicGibbsJob.jl). An example of how this Gibbs job can be utilized to sample from a bivariate normal distribution with two correlated random variables is available [here](https://github.com/JuliaStats/Klara.jl/blob/master/doc/examples/BivariateNormal/Gibbs.jl).

Although the existing Gibbs job is operational, more work is required before it can be used for sampling from hierarchical models similarly to OpenBUGS. The main goal is to be able to take as input a set of cliques (into which the graphical probabilistic model can be decomposed) and the factors associated with these cliques, and then derive the parameter associated with each node in the graph. The target of each parameter can then be fed into the existing Gibbs job or to variations of it.

Here is an incremental task list required to reach the point of being able to sample from hierarchical models:

- [x] Define a Gibbs factor, i.e. a factor product over disjoint cliques (not normalized by the associated partition function).
- [ ] Construct one variable per node in the graphical model by taking the Gibbs factor as input.
- [ ] Add an option for determining the Jacobian correction of the involved parameters according to their support.
- [ ] Add the tuner for adaptive Metropolis-within-Gibbs introduced by Roberts and Rosenthal.
- [ ] Make the `BasicGibbsJob` work by taking a `GibbsFactor` as input.
- [ ] Implement the adaptive Metropolis-within-Gibbs (AMWG) sampler by Roberts and Rosenthal. Note that this will not be a sampler in Klara terms, but a job of type `AMWGJob`.

These tasks are carried out in the gibbs branch before the issue has been resolved and merged into master.
